### ISSUE TITLE
Suggestion: Make the default script folder under the BL user directory instead of BL game/module directory

### ISSUE THREAD

**Issue by zijistark** [int19h/Bannerlord.CSharp.Scripting#1]
Great concept with the mod!

One small thing that struck me initially, however, is that your C# script path for `csx.run` is under the game (module) folder itself and not safely tucked away where all BL user config, logs, and, thanks to you, scripts should be-- under the Bannerlord user directory (on Windows & Mac, this is always a level below `Documents`, e.g.).

I could throw up some symlinks, but I'd rather not, and this is a best practice IMHO. Something like:

```
var userDir = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.Personal), "Mount and Blade II Bannerlord");
scriptDirs.Add(Path.Combine(userDir, "csx"));
```

Cheers.

**Comment by int19h** [comment]
An interesting point. Yeah, putting it side by side with the saves makes sense.

I'll need to come up with a better way to distribute the example scripts, though. Perhaps unpack them from resources if they aren't already present.

**Comment by zijistark** [comment]
Yeah, packing up the example scripts in any form (resources, any type of external archive, etc.) and then just unpacking / extracting on-the-fly when `<userdir>/csx/scripts/` doesn't exist [yet] seems like the ideal way to distribute them.

Personally, I'd just link with a broadly licensed archiving library like that of 7-Zip (or numerous others) for initiating extraction at runtime & simply add a post-build event to the project for batch-archiving every `examples/*.*` in the project root (or wherever) into one file & then distribute that archive directly with the mod. Easy to add and edit example scripts as you go. Can be manually unpacked again later if the user was overzealous in deleting too many of them at some point. Plays well with Vortex / mod managers. Nice and easy.

**Comment by zijistark** [comment]
Oh, I suppose you may need to store the MD5 manifest of the archive or otherwise version it somehow so that as updates of `csx` occur, new or modified example scripts make it into the appropriate folder at runtime.

**Comment by int19h** [comment]
In .NET, bundling is generally easiest with embedded resources - the build system takes care of embedding, and extracting them is as easy as using `Stream.CopyTo`.

**Comment by int19h** [comment]
Implemented in https://github.com/int19h/csx/commit/0b4035d286848fe994c9d143b91dbaa6b5c3b68a
